### ISSUE TITLE
CORS Issue

### ISSUE THREAD

**Issue by hanechris** [krakend/krakend-ce#137]
I have a front-end (Angular) communicating with a backend (Java) running on Windows for my dev environment.  The web app is accessed at http://localhost:8100 and the app communicates with the backed on http://localhost:8080.

This setup works fine.  When I add krakend to the middle at 8080 and change the backend to port 9898, I'm getting a CORS policy error using Chrome:

> Access to XMLHttpRequest at 'http://localhost:8080/nav/load/?app=111-111' from origin 'http://localhost:8100' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

The krakend-config.json is

```
{
  "version": 2,
  "extra_config": {
    "github_com/devopsfaith/krakend-gologging": {
      "level": "DEBUG",
      "prefix": "[KRAKEND]",
      "syslog": false,
      "stdout": true,
      "format": "default"
    },
    "github_com/devopsfaith/krakend-cors": {
      "allow_origins": [
        "*"
      ],
      "expose_headers": [
        "Content-Length"
      ],
      "max_age": "12h",
      "allow_methods": [
        "GET",
        "HEAD",
        "POST",
        "PUT",
        "DELETE",
        "CONNECT",
        "OPTIONS",
        "TRACE",
        "PATCH"
      ],
      "allow_credentials": true,
      "allow_headers": [
        "Origin",
        "Authorization",
        "Content-Type",
        "Accept",
        "X-Auth-Token"
      ]
    }
  },
  "timeout": "3000ms",
  "cache_ttl": "300s",
  "output_encoding": "json",
  "name": "Test Service",
  "endpoints": [
    {
      "endpoint": "/nav/load",
      "method": "GET",
      "extra_config": {},
      "output_encoding": "json",
      "concurrent_calls": 1,
      "backend": [
        {
          "url_pattern": "/__debug/nav/load?app=111-111",
          "encoding": "json",
          "sd": "static",
          "extra_config": {},
          "disable_host_sanitize": true,
          "host": [
            "http://localhost:9898"
          ],
          "is_collection": true,
          "target": ""
        }
      ],
      "querystring_params": []
    }
  ],
  "port": 8080
}
```

The krakend log file doesn't look like it is hitting the api-gateway or at least loging anything.  The server output from startup to after I make the call and get the error doesn't show anything in the log output to stdout
> [KRAKEND] 2019/08/28 - 14:12:59.143 ▶ ERROR unable to create the GELF writer: getting the extra config for the krakend-gelf module
> [KRAKEND] 2019/08/28 - 14:12:59.143 ▶ INFO Listening on port: 8080
> [KRAKEND] 2019/08/28 - 14:12:59.146 ▶ WARNIN building the etcd client: unable to create the etcd client: no config
> [KRAKEND] 2019/08/28 - 14:12:59.146 ▶ DEBUG creating a new influxdb client
> [KRAKEND] 2019/08/28 - 14:12:59.146 ▶ DEBUG no config for the influxdb client. Aborting
> [KRAKEND] 2019/08/28 - 14:12:59.146 ▶ WARNIN influxdb: unable to load custom config
> [KRAKEND] 2019/08/28 - 14:12:59.146 ▶ WARNIN opencensus: no extra config defined for the opencensus module
> [KRAKEND] 2019/08/28 - 14:12:59.146 ▶ DEBUG no config for the bloomfilter
> [KRAKEND] 2019/08/28 - 14:12:59.146 ▶ WARNIN bloomFilter: no config for the bloomfilter
> [KRAKEND] 2019/08/28 - 14:12:59.146 ▶ WARNIN no config present for the httpsecure module
> [KRAKEND] 2019/08/28 - 14:12:59.146 ▶ DEBUG Debug enabled
> [KRAKEND] 2019/08/28 - 14:12:59.147 ▶ DEBUG AMQP: http://localhost:9898: no amqp consumer defined
> [KRAKEND] 2019/08/28 - 14:12:59.147 ▶ DEBUG AMQP: http://localhost:9898: no amqp producer defined
> [KRAKEND] 2019/08/28 - 14:12:59.147 ▶ DEBUG CEL: no extra config detected for backend /__debug/nav/load?app=111-111
> [KRAKEND] 2019/08/28 - 14:12:59.147 ▶ DEBUG CEL: no extra config detected for pipe /nav/load
> [KRAKEND] 2019/08/28 - 14:12:59.147 ▶ INFO JOSE: singer disabled for the endpoint /nav/load
> [KRAKEND] 2019/08/28 - 14:12:59.147 ▶ INFO JOSE: validator disabled for the endpoint /nav/load
> [KRAKEND] 2019/08/28 - 14:12:59.148 ▶ INFO registering usage stats for cluster ID 'TO0zGhKWB0TArahb2q7ufqBZqX3RRXao1Hjco/mV0xM='
> [KRAKEND] 2019/08/28 - 14:12:59.172 ▶ WARNIN unable to create the usage report client: Post https://usage.krakend.io/session: dial tcp: lookup usage.krakend.io on 192.168.65.1:53: no such host

Also, if I hit http://locahost:8080/nav/load from the chrome browser directly to go through krakend to get to the backend api, I get the response back correctly.  So I figure it's an incorrect config around CORS.

Thoughts on where I'm going wrong?  Is there a way to get more debug information from the server so I can see if something is getting blocked before logging starts?

**Comment by alombarte** [comment]
Ok @hanechris,

You can do the test with a simple curl and see if the CORS headers are present or not. Doing a quick review of your configuration the krakend-cors looked good to me

**Comment by JGMAGNO** [comment]
@hanechris did you solve this?

**Comment by JGMAGNO** [comment]
I'm also experiencing this kind of error :(
