### ISSUE TITLE
Difference between sd static and dns

### ISSUE THREAD

**Issue by yanivshiloah** [krakend/krakend-ce#420]
Hey, another newbie question :)

I'm trying to figure out the difference between the different "sd" values. 
Let's say I have a microservice architecture, and locally i'm working with docker-compose and once deployed i'm working with k8s.
If I understand correctly, i'm supposed to pass "static" on local, and my host is supposed to be "http://service-name:port" and on production I should pass "dns" and my host should be my service DNS name. am I right?

However I'm currently testing krakend and I already deployed succesfully to k8s, and my "sd" was defined as "static" and host was "http://service-name", so I'm wondering what is the real difference between static and dns?

Hope you understand my question,
Thanks.

**Comment by alombarte** [comment]
Hi! I understand your question :)

Choosing DNS it does not relate to pointing to a DNS, but using DNS SRV. 

The chosen service discovery strategy determines how to retrieve (statically or dynamically) the final list of IPs, hostnames, or services pointing to your backends:

- If your host list is dynamic (the IPs and ports of your services might change in runtime), you can use an external service discovery provider with DNS SRV and let KrakenD interact with it to get the hosts.
- If your host list is static (it doesn’t change the address) or you use a service name (also kubernetes) or an external balancer, you can use static resolution and directly use the values provided under host[].

If you choose `sd: dns` it stands for `DNS SRV` and you will work with this format: https://en.wikipedia.org/wiki/SRV_record

In Kubernetes you can play with the two options, the most frequent scenario is using always static, as kubernetes transparently takes care of everything when you call a service.

Hope this helps
