### ISSUE TITLE
OpenTelemetry Support

### ISSUE THREAD

**Issue by yaronp** [krakend/krakend-ce#478]
As a user of Dynatrace, I would like that krakend-ce to support OpenTelemetry exporter integration so we can instrument, generate, collect, and export telemetry data (metrics, logs, and traces) to Dynatrace (or other OpenTelemetry supported platform).

It will also be nice if, where possible out-of-the-box instrumentation libraries will be supported (see https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrumentation).

**Comment by kpacha** [comment]
we are waiting for the project to be stable, complete and mature before switching from opencensus to opentelemetry, but it's in our roadmap.

I'm keeping this open until we switch

cheers!

**Comment by rottenbytes** [comment]
Opentelemetry is stable now right ?

**Comment by rottenbytes** [comment]
It is for traces (which is why I'm looking into it)

**Comment by alombarte** [comment]
Unfortunately, traces are a third of the requirements of this issue. This component will likely require much effort, and I don't see it implemented in CE in the short term, as OpenCensus is already providing all the functionality (and is stable). Expanding the library to onboard more providers is not a priority of the open-source product.

**Comment by iborysenko** [comment]
Hi @alombarte , according to https://opentelemetry.io/blog/2023/sunsetting-opencensus/
Make sense to add OTEL support for these project. 
Do you have any plans for it now?

**Comment by Harnoor7** [comment]
@alombarte @kpacha Is open-telemetry support in this year's roadmap or has any work started? If not, I can start working on adding Opentelemetry support to this project.

**Comment by alombarte** [comment]
Hi @Harnoor7, any help is welcome.

This year's roadmap has only two months left, so there won't be OpenTelemetry in 2023. We are about to release KrakenD 2.5, and there won't be an eventual KrakenD 2.6 until 2024.

The deprecation of OpenCensus, while OTEL does not provide (even close) the same level of stable functionality, is something I personally don't understand, but it is what it is, and we will write a new component for OTEL.

**I am reopening this task** for reference, but **the development will continue here: https://github.com/krakend/krakend-otel**

Thank you

**Comment by Harnoor7** [comment]
Currently, the opentelemetry `otelhttp` package library which is equivalent to the opencensus `ochttp` library (used in Krakend) does not expose client-side metrics which is used in Krakend [here](https://github.com/krakend/krakend-opencensus/blob/95b653439d7e4cdaae82c4cc131ff0218be29550/opencensus.go#L244). I was working on replacing ochttp with otelhttp but now will have to wait until client-side metric capture support is added as part of this [PR](https://github.com/open-telemetry/opentelemetry-go-contrib/pull/3769).

**Comment by dhontecillas** [comment]
@Harnoor7 , there is work in progress to support instrumenting the client with opentelemetry. That support will be added in a separate library, so it can be used not only in krakend-ce but also in other projects. That code will be hosted in this repo: https://github.com/krakend/krakend-otel . So, I would advice you to not move forward on adding that support until we have some basic stable implementation in that repo. You can star / watch the repo, so you get notified when we have some working implementation there.

**Comment by Harnoor7** [comment]
@dhontecillas Thanks for the update. I also did some implementation for Opentelemetry integration, Will wait for your implementation to complete then. If you don't mind, Possible to share a rough timeline as to when we can have a working implementation?

**Comment by dhontecillas** [comment]
@Harnoor7 we are actively working on it, but given that the end of the year holidays are so close, I would say that the PR in this repo will be ready by the first half of January. And it might get merged, and used in KrakenD Community in the next release.

**Comment by Harnoor-se7en** [comment]
Thanks, This helps!

**Comment by Harnoor7** [comment]
Thanks, this helps!

**Comment by alombarte** [comment]
Hello @yaronp,

With the last release, you should be able to integrate Dynatrace on KrakenD. Here are the docs: https://www.krakend.io/docs/telemetry/opentelemetry/

Please share any follow-up snippets of code, recommendations, or guidance you have once you implement it. I am closing this task.

Thank you!
