### ISSUE TITLE
Need Krakend config for Kafka as an async agent

### ISSUE THREAD

**Issue by axoxymous-coder** [krakend/krakend-ce#680]
**Environment info:**

* KrakenD version: Run `krakend help | grep Version` and copy the output here
`Version: 2.2.0`
* System info: Run `uname -srm` or write `docker` when using containers
`Linux 5.15.0-60-generic x86_64`
* Hardware specs: Number of CPUs, RAM, etc
2vCPU (Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz)
8GB RAM
* Backend technology: Node, PHP, Java, Go, etc.
Go
* Additional environment information:

**Describe what are you trying to do**:
I am trying to configure Kafka as an async agent to accomplish the following:

- Application publishes payload to a Kafka Topic, say "krakend-payload"
- Krakend Kafka Async Agent consumes the payload from the above topic
- Krakend calls a remote HTTP endpoint with the above payload
- (optional) The response of the above call is published to a different Kafka topic, say "remote-response"

Is the above even possible? I am not able to find any help or sample for configuring Kafka as an Async agent. Krakend document only tells about an AMQP async agent. Can someone help me with a correct config for Kafka async agent? 

**Your configuration file**:

```json
{
    "version": 3,
    "telemetry/logging": {
        "level": "DEBUG",
        "prefix": "[KRAKEND]",
        "syslog": false,
        "stdout": true,
        "format": "default",
        "syslog_facility": "local3"
    },
    "async_agent": [
        {
            "name": "kafka-agent",
            "connection": {
                "max_retries": 10,
                "backoff_strategy":"exponential-jitter",
                "health_interval": "10s"
            },
            "consumer": {
                "topic": "krakend",
                "workers": 1,
                "timeout": "150ms",
                "max_rate": 0.5
            },
            "backend": [
                {
                    "host": [
                        "https://httpbin.org"
                    ],
                    "url_pattern": "/post",
                    "method": "GET",
                    "encoding": "json",
                    "async": {
                        "handler": "kafka",
                        "config": {
                            "topic": "notifications",
                            "bootstrap_servers": "localhost:9092",
                            "group_id": "krakend-consumer-group"
                        }
                    }
                }
            ],
            "extra_config": {
                "async/kafka": {
                    "host": "kafka://localhost:9092/"
                }
            }
        }
    ]
}

```

**Configuration check output**:
Result of `krakend check -dtc krakend.json --lint` command

```
ERROR linting the configuration file:	jsonschema: '/async_agent/0/backend/0' does not validate with https://www.krakend.io/schema/v3.json#/properties/async_agent/$ref/items/properties/backend/items/$ref/additionalProperties: additionalProperties 'async' not allowed
```

**Commands used:**
How did you start the software?
```
krakend run -d -c async-agent.json
```

**Logs:**
Parsing configuration file: async-agent.json
2023/02/20 21:00:51 KRAKEND INFO: Starting KrakenD v2.2.0
2023/02/20 21:00:51 KRAKEND DEBUG: [SERVICE: Gin] Debug enabled
2023/02/20 21:00:51 KRAKEND INFO: Starting the KrakenD instance
2023/02/20 21:00:51 KRAKEND INFO: [SERVICE: Gin] Building the router
2023/02/20 21:00:51 KRAKEND INFO: [SERVICE: Gin] Listening on port: 8080
2023/02/20 21:00:51 KRAKEND DEBUG: [SERVICE: AsyncAgent][kafka-agent] Starting the async agent
2023/02/20 21:00:51 KRAKEND DEBUG: [ENDPOINT: kafka-agent] Building the proxy pipe
2023/02/20 21:00:51 KRAKEND DEBUG: [BACKEND: /post] Building the backend pipe
2023/02/20 21:00:56 KRAKEND DEBUG: [SERVICE: Telemetry] Registering usage stats for Cluster ID QqzTyva2CPVyQjtxJOR6h1zgEvKwJpxC7y3hmXFJgG0=

**Additional comments:**

If someone can help me with a sample json config to run KrakenD with Kafka as an async agent, it will be really appreciated.

**Comment by alombarte** [comment]
Hi @axoxymous-coder, the async agents only support Rabbit at the moment. The `extra_config` you added to the async agent it simply does not exist.
