### ISSUE TITLE
Unable to header.Copy from X-B3-Sampled to Ot-Tracer-Sampled

### ISSUE THREAD

**Issue by shariqmus** [krakend/krakend-ce#681]
**Environment info:**

Version: 2.2.0
docker
Kubernetes
Java

**Describe the bug**

I am trying to copy a request header X-B3-Sampled to a new header Ot-Tracer-Sampled. The header 'X-B3-Sampled' is generated by krakend after enabling opencensus.

I used the Martian component, however no matter what I try, the Ot-Tracer-Sampled header always ends up empty for the server in the backend. Seems like 'X-B3-Sampled' header (which appears after enabling opencensus) is never "seen" by martian to be manipulated.

If I use a different header like "X-Forwarded-For" instead of 'X-B3-Sampled', it is copied correctly.

**Your configuration file**:

```json
{
  "$schema": "https://www.krakend.io/schema/v3.json",
  "version": 3,
  "name": "KrakenD - API Gateway",
  "timeout": "3000ms",
  "cache_ttl": "300s",
  "output_encoding": "no-op",
  "debug_endpoint": true,
  "extra_config": {
    "telemetry/logging": {
      "level": "DEBUG",
      "prefix": "[KRAKEND]",
      "syslog": false,
      "stdout": true
    },
    "telemetry/opencensus": {
        "exporters": {
            "prometheus": {
                "port": 9091,
                "namespace": "krakend"
            }
        }
    }
  },
  "endpoints": [
    {
      "endpoint": "/v1",
      "method": "GET",
      "output_encoding": "no-op",
      "input_headers": [
        "User-Agent",
        "Accept",
        "X-Martian",
        "Ot-Tracer-Sampled"
      ],  
      "backend": [
        {
        "extra_config": {
          "modifier/martian": {
              "fifo.Group": {
                "scope": ["request"],
                "aggregateErrors": true,
                "modifiers": [
                    {  "header.Copy": {
                            "scope": ["request"],
                            "from": "X-Forwarded-For",
                            "to": "X-Martian"
                        }
                    },
                    {  "header.Copy": {
                      "scope": ["request"],
                      "from": "X-B3-Sampled",
                      "to": "Ot-Tracer-Sampled"
                      }
                    }
                ]
            }
          }
      },          
          "url_pattern": "/",
          "method": "GET",
          "host": [
            "http://localhost:8181"
          ]
          
        }
      ]
    }
  ]
}
```

**Commands used**
How did you start the software?
```
krakend run -c krakend.json
```
**Expected behavior**
In the below log from the backend server, 'Ot-Tracer-Sampled' should have been populated with the same value as'X-B3-Sampled' header.

```
Host: localhost:8181
User-Agent: curl/7.87.0
Accept: */*
Ot-Tracer-Sampled: 
X-B3-Sampled: 0
X-B3-Spanid: 3c454e5cd8bff78b
X-B3-Traceid: cc356acba80cecb2b94afd5efc73b51a
X-Forwarded-For: 127.0.0.1
X-Forwarded-Host: localhost:8080
X-Forwarded-Via: KrakenD Version 2.2.0
X-Martian: 127.0.0.1
Accept-Encoding: gzip
```

**Comment by alombarte** [comment]
Hi @shariqmus ,

Thanks for hanging in :)

The problem you are facing is the order in which the middlewares are stacked.

When you copy the headers using Martian, the opencensus component has not appeared yet, so you cannot copy something that it hasn't been set yet.

You can check the order of the middleware stacking here: https://github.com/krakendio/krakend-ce/blob/master/backend_factory.go

A possible solution (to investigate) is that we could inject a Lua script into the handlers you can do anything you want with the tracing information. This is not currently supported but we could consider adding it in future versions if you find it valuable.

**Comment by shariqmus** [comment]
bump
