### ISSUE TITLE
Hight goroutine count when using rate limit

### ISSUE THREAD

**Issue by hagarze** [krakend/krakend-ce#692]
**Environment info:**

* KrakenD version: 2.2.1
* System info: docker

**Describe the bug**
We have recently noticed Krakend goroutines count is very high (around 119K) from startup even when there is very low traffic.
Looks like the cause is the rate limiting configuration. When removed, the goroutine count dropped substantially to 2K.

We have about 75 endpoints with the same rate limit config.

**Your configuration file**:

```json
"qos/ratelimit/router": {
          "client_max_rate": 10,
          "strategy": "header",
          "key": "x-forwarded-for"
}
```

**Commands used**
How did you start the software?
```
ENV FC_ENABLE=1
ENV FC_SETTINGS="/etc/krakend/env"
ENV FC_PARTIALS="/etc/krakend/partials"
ENV FC_TEMPLATES="/etc/krakend/templates"
krakend run -c /etc/krakend/krakend.json
```

**Comment by hagarz** [comment]
Hi @taik0, 

Did you get a chance to test this?

Thanks,
Hagar

**Comment by taik0** [comment]
Hi @hagarz 
We are rewriting the ratelimit middleware, I'll check if this behaviour is present. I'll keep you posted!
