### ISSUE TITLE
Add "typ" attribute in JWT header when signing tokens

### ISSUE THREAD

**Issue by MinKyawNyunt** [krakend/krakend-ce#711]
**Environment info:**

* KrakenD version: 2.2.1
* System info: docker

**Describe what are you trying to do**:
Adding additional in Header

**configuration**:

```json
{
      "endpoint": "/auth/login",
      "method": "POST",
      "backend": [
        {
          "host": [
            "http://nginx:81"
          ],
          "url_pattern": "/api/login",
          "sd": "static",
          "method": "POST",
          "extra_config": {
            "backend/http": {
              "return_error_details": "auth"
            }
          }
        }
      ],
      "extra_config": {
        "auth/signer": {
          "alg": "HS256",
          "kid": "user",
          "keys_to_sign": [
            "access_token",
            "refresh_token"
          ],
          "jwk_url": "http://nginx:81/api/jwk",
          "disable_jwk_security": true
        }
      },
      "input_headers": [
        "Accept",
        "Content-Type"
      ]
    },
```
**jwt decode header output**
```json
{
  "alg": "HS256",
  "kid": "user"
}
```

**expected decode header result**
```json
{
  "alg": "HS256",
  "kid": "user"
  "typ": "JWT"
}
```

**Comment by alombarte** [comment]
Hi @MinKyawNyunt , this feature is not currently supported, but we can add it in future releases

**Comment by kpacha** [comment]
for future references, the change should go here: https://github.com/krakendio/krakend-jose/blob/master/jws.go#L141

**Comment by kpacha** [comment]
@AlyHKafoury sure! contributions are always welcome!!!

**Comment by AlyHKafoury** [comment]
would this be enough ? https://github.com/krakendio/krakend-jose/pull/119

**Comment by alombarte** [comment]
Thank you very much @AlyHKafoury for your contribution! I see there are minor changes requested in the PR, if you add them we will release this in KrakenD 2.5 which is round the corner

**Comment by AlyHKafoury** [comment]
I will work on it now and see if I can get a clear

**Comment by kpacha** [comment]
This will be released with v2.6, planned on mid Feb 2024

**Comment by AlyHKafoury** [comment]
Is there any connected issues that are urgent I can contribute to ?
________________________________

**Comment by alombarte** [comment]
Hi @AlyHKafoury , thank you for your support! There are no urgent issues, but feel free to navigate through the almost 1000 questions and requests we opened have: https://github.com/search?l=&o=asc&q=user%3Akrakend&state=open&type=Issues
I am closing this issue, as this is already integrated on the master branch.
