### ISSUE TITLE
Azure Marketplace KrakenD Community Image

### ISSUE THREAD

**Issue by psanoy** [krakend/krakend-ce#762]
**Environment info:**

* KrakenD version: Run `krakend help | grep Version` and copy the output here
root@wiv-mkt-krakend-prod:~# krakend help | grep Version
```
krakend: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by krakend)
krakend: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by krakend)
```
* System info: Run `uname -srm` or write `docker` when using containers
Linux 5.10.0-23-cloud-amd64 x86_64
* Hardware specs: Number of CPUs, RAM, etc
* Backend technology: Node, PHP, Java, Go, etc.
* Additional environment information:

**Describe what are you trying to do**:
I am just trying to get a krakenD deployment instance on Azure by using the image for the VM on the marketplace of Azure. Krakend is failing and unable to start because of the following error

```
krakend: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by krakend)
krakend: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by krakend)
```

**Your configuration file**:

```json
{
  "version": 3,
  ...
}
```

**Configuration check output**:
Result of `krakend check -dtc krakend.json --lint` command

```
Output of the linter here.
```

**Commands used:**
How did you start the software?
```
#Example:
krakend run -d -c krakend.json

# Or maybe...
docker run --rm -it -v $PWD:/etc/krakend \
        -e FC_ENABLE=1 \
        -e FC_SETTINGS="/etc/krakend/config/settings" \
        -e FC_PARTIALS="/etc/krakend/config/partials" \
        -e FC_OUT=out.json \
        devopsfaith/krakend \
        run -c /etc/krakend/config/krakend.json -d
```

**Logs:**
Logs you saw in the console and debugging information

**Additional comments:**
```
krakend: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by krakend)
krakend: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by krakend)
```

Debian 11 OS from the image and on Azure. Version for krakend seems to be 2.4.2

**Comment by kpacha** [comment]
Fixed at v2.4.3. Thanks for reporting
