### ISSUE TITLE
Unable to validate the token: should have a JSON content type for JWKS endpoint

### ISSUE THREAD

**Issue by tiagogameiro-diconium** [krakend/krakend-ce#766]
**Environment info:**
Version: 2.4.3
Java

**Describe the bug**
When trying to validate a token using a public keys URL that returns a Content-Type header with value `application/jwk-set+json`, krakend rejects the request with the following error:
`Unable to validate the token: should have a JSON content type for JWKS endpoint`.

This is not the case when the Content-Type returned is "application/json".
Is this intended behavior?

**Comment by alombarte** [comment]
Currently only the `application/json` content type is accepted. Nevertheless you can easily change this in KrakenD using a martian modifier that changes the content type. For instance:

```
{
  "version": 3,
  "$schema": "https://www.krakend.io/schema/v3.json",
  "endpoints": [
    {
      "endpoint": "/jwk",
      "output_encoding": "no-op",
      "backend": [
        {
          "host": [
            "https://your-idp"
          ],
          "url_pattern": "/.well-known/jwks.json",
          "extra_config": {
            "modifier/martian": {
              "header.Modifier": {
                "scope": [
                  "response"
                ],
                "name": "Content-Type",
                "value": "application/json"
              }
            }
          }
        }
      ]
    },
    {
      "endpoint": "/protected",
      "extra_config": {
        "auth/validator": {
          "alg": "RS256",
          "jwk_url": "http://localhost:8080/jwk",
          "disable_jwk_security": true,
          "operation_debug": true
        }
      },
      "backend": [
        {
          "url_pattern": "/__debug/"
        }
      ]
    }
  ]
}
```

**Comment by tiagogameiro-diconium** [comment]
Hello @alombarte thanks for the help, I wasn't aware of the martian modifier functionality.
II tried to apply your solution and I was able to successfully change the header on the response but only when the `jwt_url` was being fetched locally. If i update it to the real external idp .well-known url, then I am not able to configure the endpoint to change the response. I believe I am missing something in the configuration.

Here's an example:
```
[
    {
      "endpoint": "/external-idp.com/.well-known/jwks.json",
      "output_encoding": "no-op",
      "backend": [{
          "host": [
            "https://external-idp.com"
          ],
          "url_pattern": "/.well-known/jwks.json",
          "extra_config": {
            "modifier/martian": {
              "header.Modifier": {
                "scope": [
                  "response"
                ],
                "name": "Content-Type",
                "value": "application/json"
              }
            }
          }
        }
      ]
    },
    {
      "endpoint": "/protected",
      "method": "GET",
      "output_encoding": "no-op",
      "extra_config": {
        "auth/validator": {
          "alg": "ES256",
          "jwk_url": "https://external-idp.com/.well-known/jwks.json",
          "operation_debug": true,
          "disable_jwk_security": true
        }
      },
      "backend": [
        {
          "url_pattern": "/protected",
          "method": "GET",
          "encoding": "no-op",
          "host": [
            "http://localhost:8081" //my application service running locally behind the gateway
          ]
        }
      ]
    }
  ]
``` 
Is it possible to change the header of the external-idp response if that one is not managed by me? I am unsure of what to set on the first endpoint path (in the example with /external-idp.com/.well-known/jwks.json).

**Comment by dhontecillas** [comment]
this will be addressed in https://github.com/krakend/krakend-jose/pull/126
