### ISSUE TITLE
krakend-integration Binary Installation Fails due to replace Directives in go.mod File

### ISSUE THREAD

**Issue by thinkingabouther** [krakend/krakend-ce#769]
**Environment info:**
* KrakenD version: 2.4.3
* Environment: Docker container with golang:1.21

**Issue description**
`krakend-integration` binary cannot be installed the way described in the [integration tests documentation](https://www.krakend.io/docs/developer/integration-tests/#installing-the-integration-tests-tool). It appears that the the `replace` directives in `go.mod` file are causing the installation to fail

**Steps to Reproduce**
Run the following command: 
```
go install github.com/krakend/krakend-ce/v2/cmd/krakend-integration@v2.4.3
```

**Expected behavior**
The `krakend-integration` binary should be installed in the PATH, making it readily available for running integration tests.

**Actual behavior**
The installation fails with the following error message:
```
#6 0.884 go: downloading github.com/krakend/krakend-ce/v2 v2.4.3
#6 1.325 go: github.com/krakend/krakend-ce/v2/cmd/krakend-integration@v2.4.3 (in github.com/krakend/krakend-ce/v2@v2.4.3):
#6 1.325        The go.mod file for the module providing named packages contains one or
#6 1.325        more replace directives. It must not contain directives that would cause
#6 1.325        it to be interpreted differently than if it were the main module.
```

**Comment**
If there's an alternate method to conduct the integration tests, it would be helpful to include this in the Integration Tests Documentation to assist users who encounter similar issues.

**Comment by oscar6662** [comment]
I have the same issue.
