### ISSUE TITLE
Reserved characters in URLs

### ISSUE THREAD

**Issue by farhanfaiz05** [krakend/krakend-ce#771]
i have the following endpoint that needs to be added in krakend.

endpoint : /v1/abcd/{var}.json
backend : /abcd/{var}.json

When i access the endpoint using https://example.com/v1/abcd/en.json , the krakend access logs is showing the endpoint correctly as /v1/abcd/en.json , but the backend service to which this request is routed is not correctly receiving it. The access log of backend service is showing as "/v1/abcd/%7B%7B.Lang%7D%7D.json"

How can i make this work correctly?

**Comment by alombarte** [comment]
For reference, an extra parameter is needed: https://www.krakend.io/docs/backends/#disable-restful-checking
