### ISSUE TITLE
Support for h2c protocol (clear text HTTP/2) is not working

### ISSUE THREAD

**Issue by jaimenavarro** [krakend/krakend-ce#772]
**Environment info:**
* KrakenD version: **v2.4.3** (devopsfaith/krakend:watch) (https://github.com/krakend/playground-community)
* System info: **docker**
```
Client:
 Version:           24.0.2-rd
 API version:       1.42 (downgraded from 1.43)
 Go version:        go1.20.4
 Git commit:        e63f5fa
 Built:             Fri May 26 16:39:47 2023
 OS/Arch:           darwin/amd64
 Context:           default

Server:
 Engine:
  Version:          23.0.6
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       9dbdbd4b6d7681bd18c897a6ba0376073c2a72ff
  Built:            Fri May 12 13:54:36 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.0
  GitCommit:        1fbd70374134b891f97ce19c70b6e50c7b9f4e0d
 runc:
  Version:          1.1.7
  GitCommit:        860f061b76bb4fc671f0f9e900f7d80ff93d4eb7
 docker-init:
  Version:          0.19.0
  GitCommit:
```
* Hardware specs: 
  * MacOS Ventura 13.5
  * 2 GHz Intel Core i5 de 4 núcleos
  * 16 GB 3733 MHz LPDDR4X

**Describe the bug**

- In release [v2.3.0](https://github.com/krakend/krakend-ce/releases/tag/v2.3.0) this feature **h2c protocol (clear text HTTP/2)** was added. And it seems to be that **it's not working.**
```[feature] Added h2c protocol (clear text HTTP/2), in addition to the already supported HTTP/2 over TLS```

**Your configuration file**:
- The same one used in playground-community, https://github.com/krakend/playground-community/blob/master/config/krakend/krakend.json

**Commands used**
How did you start the software?
- I've used the playground community repo(https://github.com/krakend/playground-community)
```
make start
```

**Expected behavior**
I was expecting an HTTP code 200 due to the fact that **the h2c protocol (clear text HTTP/2) is supported from v2.3.0**
```
curl -v http://localhost:8080/public --http2-prior-knowledge
```

**Current behavior**
The only option in which I get a good response is when I send a request using protocol HTTP1. **If I try to use HTTP2 in CLEAR then I get the following error**, by the way, I can't see any error logs on the KrakenD side regarding this problem.
```
curl -v http://localhost:8080/public --http2-prior-knowledge
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
* h2 [:method: GET]
* h2 [:scheme: http]
* h2 [:authority: localhost:8080]
* h2 [:path: /public]
* h2 [user-agent: curl/8.1.2]
* h2 [accept: */*]
* Using Stream ID: 1 (easy handle 0x7f8ecf011600)
> GET /public HTTP/2
> Host: localhost:8080
> User-Agent: curl/8.1.2
> Accept: */*
>
* Closing connection 0
curl: (56) Failure when receiving data from the peer
```

**Comment by kpacha** [comment]
The configuration included in the playground doesn't enable the `h2c` flag. Check the documentation for more details on how to enable it: https://www.krakend.io/docs/service-settings/router-options/#use_h2c

**Comment by jaimenavarro** [comment]
Thanks for your help @kpacha
