### ISSUE TITLE
Why krakend executing setgroups command?

### ISSUE THREAD

**Issue by osama-ahmed-wiz** [krakend/krakend-ce#781]
**Environment info:**

* OpenShift server
* Docker container

**Describe what are you trying to do**:
I am using the krakend docker image 2.0.4 which is working fine but after upgrading it to 2.4.3, It is trying to execute setgroups command which is not permitted.
Container is running as non-root user.

Error: su-exec: setgroups: Operation not permitted

Is there any way to run it as non-root user?

**Logs:**
su-exec: setgroups: Operation not permitted

**Additional comments:**
It is working fine on 2.1.2 as well but after onward getting this error.

![image](https://github.com/krakend/krakend-ce/assets/106302788/f1fe83e6-8dbc-46e5-ba80-696f5178c923)

**Comment by taik0** [comment]
Hi @osama-ahmed-wiz 
We added an entrypoint to follow the official Docker directives.
You need to add this to your deployment:
``` 
securityContext:
          runAsNonRoot: true
          runAsUser: 1000
```
