### ISSUE TITLE
can't build from windows 11

### ISSUE THREAD

**Issue by LIANGQI0811** [krakend/krakend-ce#790]
**Environment info:**

* KrakenD version: krakend-ce from tag v2.4.3
* System info: windows 11
* Hardware specs: 16 cores, and 32GB memory
* Backend technology: Java, Go
* Additional environment information:

**Describe the bug**
I failed when trying to build using Windows 11 (please see the picture for the error message). After investigation, I found that go did not implement the relevant functions under Windows.
Why don't we use slog instead of log?

**Additional context**
![image](https://github.com/krakend/krakend-ce/assets/16715787/fb4fb379-babf-45d8-987c-aeb3d18d789c)

**Comment by kpacha** [comment]
There are other limitations in windows, so we decided to not support it. You can use the dockerized version
