### ISSUE TITLE
 invalid node type

### ISSUE THREAD

**Issue by esmaily** [krakend/krakend-ce#800]
**Environment info:**

* KrakenD version:   2.4.3
* System info:   Linux 6.1.0-12-amd64 x86_64 
* Backend technology: Python.

I get this error when send post request to get endpoint or send get request for post endpoint.
Why occur this error? please help me

2023/10/18 18:24:06 http: panic serving 172.22.0.1:49362: invalid node type
krakendAdmin  | goroutine 209 [running]:
krakendAdmin  | net/http.(*conn).serve.func1()
krakendAdmin  |         /usr/local/go/src/net/http/server.go:1854 +0xbf
krakendAdmin  | panic({0x2963b40, 0x3569840})
krakendAdmin  |         /usr/local/go/src/runtime/panic.go:890 +0x263
krakendAdmin  | github.com/gin-gonic/gin.(*node).findCaseInsensitivePathRec(0x0?, {0xc000168109?, 0x0?}, {0xc00017ab80?, 0x0?, 0x0?}, {0x2f, 0x0, 0x0, 0x0}, ...)
krakendAdmin  |         /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/tree.go:862 +0xa9d
krakendAdmin  | github.com/gin-gonic/gin.(*node).findCaseInsensitivePathRec(0x0?, {0xc000168108?, 0x0?}, {0xc00017ab80?, 0x0?, 0x0?}, {0x2f, 0x0, 0x0, 0x0}, ...)
krakendAdmin  |         /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/tree.go:778 +0x45d
krakendAdmin  | github.com/gin-gonic/gin.(*node).findCaseInsensitivePathRec(0xc000e1b0a0?, {0xc000168104?, 0x12?}, {0xc00017ab80?, 0x10?, 0x80?}, {0x73, 0x0, 0x0, 0x0}, ...)
krakendAdmin  |         /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/tree.go:778 +0x45d
krakendAdmin  | github.com/gin-gonic/gin.(*node).findCaseInsensitivePathRec(0xc000d5a400?, {0xc0001680fe?, 0xffdb31?}, {0xc00017ab80?, 0xc000164000?, 0x0?}, {0x75, 0x0, 0x0, 0x0}, ...)
krakendAdmin  |         /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/tree.go:778 +0x45d
krakendAdmin  | github.com/gin-gonic/gin.(*node).findCaseInsensitivePathRec(0xc0007445a0?, {0xc0001680fa?, 0xf28bc5?}, {0xc00017ab80?, 0xf1237e?, 0x7fe7612e00a8?}, {0x61, 0x0, 0x0, 0x0}, ...)
krakendAdmin  |         /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/tree.go:778 +0x45d
krakendAdmin  | github.com/gin-gonic/gin.(*node).findCaseInsensitivePathRec(0x11f9e45?, {0xc0001680f9?, 0xf18ba3?}, {0xc00017ab80?, 0xc00012cda0?, 0xc00012cda0?}, {0x31, 0x0, 0x0, 0x0}, ...)
krakendAdmin  |         /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/tree.go:778 +0x45d
krakendAdmin  | github.com/gin-gonic/gin.(*node).findCaseInsensitivePathRec(0xc000086838?, {0xc0001680f5?, 0xc000086700?}, {0xc00017ab80?, 0xc0001680f0?, 0xc0000868b0?}, {0x76, 0x0, 0x0, 0x0}, ...)
krakendAdmin  |         /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/tree.go:778 +0x45d
krakendAdmin  | github.com/gin-gonic/gin.(*node).findCaseInsensitivePathRec(0x0?, {0xc0001680f4?, 0x0?}, {0xc00017ab80?, 0xc000d8b275?, 0xf1b7d0?}, {0x61, 0x0, 0x0, 0x0}, ...)
krakendAdmin  |         /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/tree.go:778 +0x45d
krakendAdmin  | github.com/gin-gonic/gin.(*node).findCaseInsensitivePath(0xc0001680f4?, {0xc0001680f4, 0x22}, 0x40?)
krakendAdmin  |         /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/tree.go:669 +0x9c
krakendAdmin  | github.com/gin-gonic/gin.redirectFixedPath(0xc000537e00, 0xc0001680f4?, 0x55?)
krakendAdmin  |         /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:691 +0x5b
krakendAdmin  | github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc0008fcd00, 0xc000537e00)
krakendAdmin  |         /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:629 +0x3aa
krakendAdmin  | github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc0008fcd00, {0x358d5a0?, 0xc00055ae00}, 0xc0005a8000)
krakendAdmin  |         /go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 +0x1dd
krakendAdmin  | net/http.serverHandler.ServeHTTP({0xc000ce08d0?}, {0x358d5a0, 0xc00055ae00}, 0xc0005a8000)
krakendAdmin  |         /usr/local/go/src/net/http/server.go:2936 +0x316
krakendAdmin  | net/http.(*conn).serve(0xc000d82ab0, {0x358ecc8, 0xc000f2b890})
krakendAdmin  |         /usr/local/go/src/net/http/server.go:1995 +0x612
krakendAdmin  | created by net/http.(*Server).Serve
krakendAdmin  |         /usr/local/go/src/net/http/server.go:3089 +0x5ed

**Comment by alombarte** [comment]
@esmaily you haven't included the configuration you are using. Impossible to help.

**Comment by esmaily** [comment]
Dear @alombarte 

configuration file: 
`
{
  "$schema": "https://www.krakend.io/schema/v3.json",
  "version": 3,
  "endpoints": [
    {
      "endpoint": "/api/v1/admin/users/active-user",
      "output_encoding": "no-op",
      "method": "PUT",
      "input_query_strings": [
        "*"
      ],
      "input_headers": [
        "*"
      ],
      "backend": [
        {
          "url_pattern": "api/v1/admin/users/active-user",
          "method": "PUT"
        }
      ]
    },
    {
      "endpoint": "/api/v1/admin/users/unlock",
      "output_encoding": "no-op",
      "method": "POST",
      "input_query_strings": [
        "*"
      ],
      "input_headers": [
        "*"
      ],
      "backend": [
        {
          "url_pattern": "api/v1/admin/users/unlock",
          "method": "POST"
        }
      ]
    },
    {
      "endpoint": "/api/v1/admin/users/check/user",
      "output_encoding": "no-op",
      "method": "POST",
      "input_query_strings": [
        "*"
      ],
      "input_headers": [
        "*"
      ],
      "backend": [
        {
          "url_pattern": "api/v1/admin/users/check/user",
          "method": "POST"
        }
      ]
    },
 
    {
      "endpoint": "/api/v1/admin/users/check/otp",
      "output_encoding": "no-op",
      "method": "POST",
      "input_query_strings": [
        "*"
      ],
      "input_headers": [
        "*"
      ],
      "backend": [
        {
          "url_pattern": "api/v1/admin/users/check/otp",
          "method": "POST"
        }
      ]
    } 
  ]
}
`
