### ISSUE TITLE
How can i implement somewhat of own file server

### ISSUE THREAD

**Issue by ArkhipovK** [krakend/krakend-ce#813]
Hello im trying to implement http-client plugin that returns some data from file within the krarend docker container it self - without actual backend (like a static stub but from local file).
What should i do inside handler function that will prevent endpoint from further call of backend and just return modified response back to user.

**Comment by alombarte** [comment]
Hi @ArkhipovK, this is an Enterprise feature: https://www.krakend.io/docs/enterprise/endpoints/serve-static-content/

We don't provide directions to mimic Enterprise features.

**Comment by ArkhipovK** [comment]
> We don't provide directions to mimic Enterprise features.
But if need for some other reason prevent backend call what should i do?

**Comment by alombarte** [comment]
Fork the code and review how the [Lura Project](https://github.com/luraproject/lura) works.
