### ISSUE TITLE
Feature Request: Support for Server-Sent Events (SSE) in KrakenD API Gateway

### ISSUE THREAD

**Issue by giosueDelgado** [krakend/krakend-ce#822]
### Version of KrakenD you are using
Latest

### Is your feature request related to a problem? Please describe.
I have encountered limitations while trying to implement real-time data features in my applications using KrakenD. The lack of support for Server-Sent Events (SSE) means that I cannot efficiently push updates to clients. Currently, clients have to poll the server for updates, which is inefficient and not suitable for real-time applications.

### Describe the solution you'd like
I propose that KrakenD adds support for Server-Sent Events (SSE). This feature would enable the server to push data to clients as soon as it becomes available. Implementing SSE would greatly enhance KrakenD's capability in handling real-time data streaming, making it more versatile for applications that require instant data updates.

### Describe alternatives you've considered
While WebSockets could be an alternative, they require a more complex setup and are overkill for unidirectional data flow scenarios. SSE is simpler to implement and more resource-efficient for server-to-client communication.

### Additional context
Adding SSE support would align KrakenD with modern web development practices. It's noteworthy that some of KrakenD's competitors already support SSE, giving them an advantage in scenarios where real-time data streaming is crucial. This feature would be especially beneficial for applications like live dashboards, news feeds, and any situation where quick information delivery is essential.

**Comment by alombarte** [comment]
Hi @giosueDelgado ,

KrakenD has no plans in the short-medium term to support SSE. There are other API gateway products that do, but they are also just proxies. KrakenD is an aggregator by default and would require a different approach (e.g.: In WebSockets, we do multiplexing). 

The effort this task requires is huge. So far, we have seen very little support or interest in the community or paid customers demanding this technology (see https://github.com/krakend/krakend-ce/issues/208#issuecomment-1046908001)

I am closing because it won't be supported any time soon.

**Comment by giosueDelgado** [comment]
> Hi @giosueDelgado ,
> 
> KrakenD has no plans in the short-medium term to support SSE. There are other API gateway products that do, but they are also just proxies. KrakenD is an aggregator by default and would require a different approach (e.g.: In WebSockets, we do multiplexing).
> 
> The effort this task requires is huge. So far, we have seen very little support or interest in the community or paid customers demanding this technology (see [#208 (comment)](https://github.com/krakend/krakend-ce/issues/208#issuecomment-1046908001))
> 
> I am closing because it won't be supported any time soon.

Hi @alombarte thanks for your response.
For sure we and our clients will use another api gateway because is not supported. 

In my opinion I think that add SSE can be a good think to complete the feature for an API Gateway.
Maybe in the first version you can add the feature support not managing the aggregator but only as a proxy.. and in the next version improve based on the feedback. Maybe many people not ask the feature because are using other tool for this..

Anyway thanks for support, hope in the future this tool can be a 360° solution for an API Gateway! :-)
