### ISSUE TITLE
When returning error from request modifier from backend, skips the response aggregation step.

### ISSUE THREAD

**Issue by eminaktas** [krakend/krakend-ce#825]
**Environment info:**

* KrakenD version: 2.5.0
* System info: docker

**Describe the bug**

Whenever I return an error from requests modifier in backend, it won't trigger the response modifiers in endpoint. This might be an intended behaviour but since I wan't to aggregate the errors as well. This force me to trick the KrakenD with another plugin.

For example; as you will see in the below configuration, I am running `request-controller` plugin which will allow me to select a backend. Sometimes it is possible to get a connection error or some other error within this plugin but when I return any error from that plugin, the `error-aggregator` plugin in endpoint won't be triggered. KrakenD basically returns its default behaviour.

**Your configuration file**:

```json
{
  "version": 3,
  ...
        {
            "endpoint": "an-endpoint",
            "method": "GET",
            "extra_config": {
                "plugin/req-resp-modifier": {
                    "name": ["error-aggregator"]
                }
            },
            "backend": [
                {
                    "method": "GET",
                    "sd": "static",
                    "host": [
                        "a-host"
                    ],
                    "url_pattern": "a-url-pattern",
                    "encoding": "json",
                    "is_collection": true,
                    "mapping": {
                        "collection": "backend-1"
                    },
                    "extra_config": {
                        "backend/http": {
                            "return_error_details": "backend-1"
                        },
                        "plugin/req-resp-modifier": {
                            "name": ["request-controller"]
                        }
                    }
                }
            ],
.....
        }
}
```

**Expected behavior**

Like in the response modifier plugins whenever I return error from the plugin, I'd like to see that the other plugins were still triggered. This way I'll be able to still return error and aggregate none-errored backends.

**Comment by alombarte** [comment]
Any error aborts the pipeline, so this is expected behavior
