### ISSUE TITLE
[HELP] make build fails with error = untyped int constant as int value in assignment (overflows)

### ISSUE THREAD

**Issue by jd-apprentice** [krakend/krakend-ce#829]
**Environment info:**

* KrakenD version: N/A
* System info: Linux 5.15.0-83-generic x86_64
* Hardware specs: R5 2600, 16gb RAM, NVM 240GB, GTX 1660
* Backend technology: N/A
* Additional environment information:

**Describe what are you trying to do**:

I'm trying to build Krakend for `armv7` inside a dockerfile with the `make build` command but i'm having the following issue

```
341.9 # github.com/luraproject/lura/v2/async
341.9 /go/pkg/mod/github.com/luraproject/lura/v2@v2.4.0/async/asyncagent.go:81:34: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in assignment (overflows)
342.0 # github.com/krakendio/krakend-amqp/v2
342.0 /go/pkg/mod/github.com/krakendio/krakend-amqp/v2@v2.1.0/consumer.go:47:20: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in assignment (overflows)
342.0 /go/pkg/mod/github.com/krakendio/krakend-amqp/v2@v2.1.0/producer.go:64:20: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in assignment (overflows)
528.5 make: *** [Makefile:59: build] Error 1
 ```

The dockerfile i'm using is kinda the same as the repository with pinned versions:

```dockerfile
FROM golang:alpine3.18 AS builder

RUN apk add --no-cache git=2.40.1-r0 make=4.4.1-r1 gcc=12.2.1_git20220924-r10 musl-dev=1.2.4-r2 binutils-gold=2.40-r7 && \
    rm -rf /var/cache/apk/*

COPY . /app
WORKDIR /app

RUN git clone https://github.com/krakend/krakend-ce.git && \
    cd krakend-ce && \
    make build

FROM alpine:3.18 as runner

RUN apk add --no-cache ca-certificates tzdata && \
    adduser -u 1000 -S -D -H krakend && \
    mkdir /etc/krakend && \
    echo '{ "version": 3 }' > /etc/krakend/krakend.json

COPY --from=builder /app/krakend /usr/bin/krakend

USER 1000

WORKDIR /etc/krakend

ENTRYPOINT ["/usr/bin/krakend"]
CMD ["run", "-c", "/etc/krakend/krakend.json"]

EXPOSE 8080 8090
```

And then to build i'm using these commands:

```make
instance:
	docker buildx create --name armv7 \
          --platform "linux/arm/v7" \
          --driver "docker-container"

use:
	docker buildx use armv7

build:
	docker buildx build \
         --platform "linux/arm/v7" \
         --tag dyallo/$(IMAGE_NAME):$(IMAGE_TAG) \
	 --push docker/$(IMAGE_NAME) \
	 --no-cache
```

Then I run `make build IMAGE_NAME="krakend" and use the dockerfile from above

I guess it has to do with those 3 files mentioned above in the lines for example [here](https://github.com/krakend/krakend-amqp/blob/master/consumer.go#L46C1-L48C3)

If is only add typings like the error says I can try to do it myself (I don't do golang but i'll give it a try haha) else if anyone can help me build this image i'll be glad to help with anything I can!

(Final goal is to be able to use Krakend on my raspberry pi zero 2 w that runs ARMv7)

**Comment by taik0** [comment]
Hi @jd-apprentice 

You are trying to build a 32-bit binary, which is not supported. You can try to fork and remove the dependencies that trigger the explicit usage of 64 bits (like the one you mentioned).

**Comment by jd-apprentice** [comment]
> Hi @jd-apprentice
> 
> You are trying to build a 32-bit binary, which is not supported. You can try to fork and remove the dependencies that trigger the explicit usage of 64 bits (like the one you mentioned).

Ohh makes sense then hahah, I'll give it a try! Will I have to change or just remove those dependencies?

**Comment by jd-apprentice** [comment]
Hey! I ended up doing the migration to a 64bits system. I'll close this but I appreciate the response, thanks for your time!
