### ISSUE TITLE
Create a queue in rabbitmq

### ISSUE THREAD

**Issue by zaer73** [krakend/krakend-ce#838]
Environment info:
KrakenD version: Version: 2.5.0
System info: docker

Describe the bug:
In rabbitmq when calling api, according to krakend exchange and queue should be created.
But exchange is created. Its queue and binding are not created based on Routing key.
As a result, the message is not queued.

configuration file:
{
  "$schema": "https://www.krakend.io/schema/krakend.json",
  "version": 3,
  "name": "KrakenD - API Gateway",
  "timeout": "3000ms",
  "cache_ttl": "300s",
  "output_encoding": "json",
  "endpoints": [
    {
      "endpoint": "/test/{reply_to}/{mess_id}/{route}",
      "method": "POST",
      "output_encoding": "no-op",
      "backend": [
        {
          "sd": "static",
          "encoding": "json",
	  "disable_host_sanitize": true,
          "extra_config": {
           "backend/amqp/producer": {
          "name": "queue",
          "exchange": "exchange",
          "durable": true,
          "delete": false,
          "exclusive": false,
          "no_wait": true,
          "mandatory": false,
          "immediate": false,
          "reply_to_key":"Reply_to",
          "msg_id_key":"Mess_id",
          "routing_key":"Route"
            }
          },
          "host": [
            "amqp://user:user@server:5672/"
          ]
        }
      ],
      "input_query_strings": [
        "*"
      ],
      "input_headers": [
        "*"
      ]
    }
  ]
}

Commands used:
The api is called through postman. Has json body, for example {"test ":"name"}

Expected behavior:
Krakend will automatically create the exchange and queue and its settings. so that the message is properly queued.

**Comment by taik0** [comment]
Hi @zaer73 

Can you open this issue in the https://github.com/krakend/krakend-amqp repo and share some logs about it?
