### ISSUE TITLE
Moving token from querystring to header before validate it

### ISSUE THREAD

**Issue by thinkingmik** [krakend/krakend-ce#843]
Hello,

I'm using Krakend `2.1.2` and I'm using `jose` lib for validating the JWT.

In certain case I have the JWT in the querystring of the request instead in the header. For example:
```
https://localhost/gateway/map?token=eyJhb...
``` 

I would know if is it possible to move the token from querystring to header `Authorization` before the `jose` lib try to validate the token?

I tried with a lua script using `modifier/lua-endpoint` with `pre` at the endpoint level, but Krakend tell me that there isn't token to validate in the request.

```lua
"modifier/lua-endpoint": {
  "pre": "local req = ctx.load(); req:headers('Authorization', 'bearer ' .. req:query('token'));"
}
```

Thanks.

**Comment by alombarte** [comment]
Hello @thinkingmik ,

The JWT validation happens before the Lua script is executed. You can see this here: https://www.krakend.io/docs/design/execution-flow/

You can move the same modifier in the `extra_config` of the service level (root), and the endpoint will receive the authorization header. This, of course, acts on all endpoints.

If you need the solution for a single endpoint, you can also create two endpoints: a public one with no JWT and the Lua script that connects to another with the validation (this would be Krakend using Krakend as backend)

**Comment by thinkingmik** [comment]
Thanks!
