### ISSUE TITLE
Update the plugins samples 

### ISSUE THREAD

**Issue by ridgarou** [krakend/krakend-ce#872]
Hello everyone,

You announced these new features with the 2.6.0 release:

- All plugins have now the KrakenD context, allowing you to perform operations during shutdown
- Request and response modifier plugins have now access to the HTTP context. Reponse modifiers have also access to the internal request, knowing low-level details like which backend was selected.

Could you update the documentation to show the use of these contexts in each case?

Thank you very much

**Comment by kpacha** [comment]
We are in the process to do so, but in the meantime you can use this PR to the example repo: https://github.com/krakend/examples/pull/1
