### ISSUE TITLE
Error installing the integration test tool in v2.6.1

### ISSUE THREAD

**Issue by torresdiego** [krakend/krakend-ce#873]
I'm trying to install the `krakend-integration` tool, using the instructions in the [documentation](https://www.krakend.io/docs/developer/integration-tests/). I'm building a docker image using Go 1.22.2

```
 > [ 6/21] RUN go install github.com/krakend/krakend-ce/v2/cmd/krakend-integration@v2.6.1:
#9 1.200 go: downloading github.com/krakend/krakend-ce/v2 v2.6.1
#9 5.344 go: github.com/krakend/krakend-ce/v2/cmd/krakend-integration@v2.6.1: version constraints conflict:
#9 5.344        github.com/krakend/krakend-ce/v2@v2.6.1: parsing go.mod:
#9 5.344        module declares its path as: github.com/krakendio/krakend-ce/v2
#9 5.344                but was required as: github.com/krakend/krakend-ce/v2
```

The same occurs if I run the command on my mac with Go 1.18.
Am I missing something?

**Comment by alombarte** [comment]
Hi @torresdiego ,

The documentation is wrong; we will correct it. Use `go install github.com/krakendio/krakend-ce/v2/cmd/krakend-integration@v2.6.1` instead
