### ISSUE TITLE
Ubuntu 22.04 setup - unable to add keyring: apt-key failed with message "keyserver receive failed: end of file"

### ISSUE THREAD

**Issue by birbygit** [krakend/krakend-ce#879]
Hello, I'm trying to install Krakend on Ubuntu 22.04
I'm following the official guide for Debian based distro on https://www.krakend.io/docs/overview/installing/
Issued commands:

```
sudo apt install -y ca-certificates gnupg
ca-certificates is already the newest version (20230311ubuntu0.22.04.1).
ca-certificates set to manually installed.
gnupg is already the newest version (2.2.19-3ubuntu2.2).
gnupg set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 5DE6FD698AD6FDD2
Executing: /tmp/apt-key-gpghome.AZShtIgpeb/gpg.1.sh --keyserver keyserver.ubuntu.com --recv 5DE6FD698AD6FDD2
gpg: keyserver receive failed: End of file
```
I received same error on Ubuntu 20.04 also; since apt-key is officially deprecated, what is the recommended way to install Krakend on such os ?

Thanks.

**Comment by taik0** [comment]
Hi @birbygit 

I have no problem installing on Ubuntu 22.04:
```
root@bc0cc8b90fe8:/# apt-key adv --keyserver keyserver.ubuntu.com --recv 5DE6FD698AD6FDD2
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
Executing: /tmp/apt-key-gpghome.aj97ve5IUI/gpg.1.sh --keyserver keyserver.ubuntu.com --recv 5DE6FD698AD6FDD2
gpg: key 5DE6FD698AD6FDD2: public key "Devops Faith Package Manager <packages@devops.faith>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```

**Comment by birbygit** [comment]
> Hi @birbygit
> 
> I have no problem installing on Ubuntu 22.04:
> 
> ```
> root@bc0cc8b90fe8:/# apt-key adv --keyserver keyserver.ubuntu.com --recv 5DE6FD698AD6FDD2
> Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
> Executing: /tmp/apt-key-gpghome.aj97ve5IUI/gpg.1.sh --keyserver keyserver.ubuntu.com --recv 5DE6FD698AD6FDD2
> gpg: key 5DE6FD698AD6FDD2: public key "Devops Faith Package Manager <packages@devops.faith>" imported
> gpg: Total number processed: 1
> gpg:               imported: 1
> ```

Hi taik0, thanks for your feedback.
I noted that you issued the commands as root: why? sudo is not enough? 
Anyway, is possible to install krakend by downloading the tar.gz file? 

The server where I've to setup Krakend is managed by my client and is under strict security policy so I cannot login as root user.
Thanks.

**Comment by alombarte** [comment]
Hi @birbygit ,

It shows root because it is the official Ubuntu Docker container. Yes, you can use the tar.gz file. The difference with package managers is that you only get the binary, so you must create the service that auto-starts the gateway on server restart.
