### ISSUE TITLE
Golang version mismatch between 2.70 krakend Docker release and krakend/builder

### ISSUE THREAD

**Issue by 0xMattijs** [krakend/krakend-ce#910]
**Environment info:**

* KrakenD version: 2.7.0
* System info: Darwin AMD64
* Hardware specs: 8-core, 32GB
* Backend technology: Go
* Additional environment information:

**Describe the bug**
There seems to be a version mismatch between the golang version used for building krakend in the Docker 2.7.0 release  (devopsfaith/krakend:2.7.0) and the Go version used in [krakend/builder](https://hub.docker.com/r/krakend/builder) version 2.7.0.

The krakend Docker release is built with Go version 1.22.2:
```
docker run -ti devopsfaith/krakend:2.7.0 version
KrakenD Version: 2.7.0
Go Version: 1.22.2
Glibc Version: MUSL-1.2.4_(alpine-3.18.6)
```

While the builder is using Go version 1.22.5:

```
docker run -it -v "$PWD:/app" -w /app krakend/builder:2.7.0 go version
go version go1.22.5 linux/amd64
```

**Commands used**
How did you start the software?
```
docker run -it -v "$PWD:/app" -w /app \
krakend/builder:2.7.0 \
go build -buildmode=plugin -o my-plugin.so .
```
And running krakend:
```
docker run -p "8080:8080" -v $PWD:/etc/krakend/ devopsfaith/krakend:2.7.0 run -c krakend.json run
```

**Expected behavior**
Succesful loading of the plugin

**Logs**
```
2024/07/20 14:32:42 KRAKEND DEBUG: [SERVICE: Executor Plugin] plugin #0 (/etc/krakend/my-plugin.so): plugin.Open("/etc/krakend/my-plugin.so"): plugin was built with a different version of package internal/godebugs
2024/07/20 14:32:42 KRAKEND DEBUG: [SERVICE: Handler Plugin] plugin #0 (/etc/krakend/my-plugin.so): plugin.Open("/etc/krakend/my-plugin.so"): plugin was built with a different version of package internal/godebugs (previous failure)
2024/07/20 14:32:42 KRAKEND DEBUG: [SERVICE: Modifier Plugin] plugin #0 (/etc/krakend/my-plugin.so): plugin.Open("/etc/krakend/my-plugin.so"): plugin was built with a different version of package internal/godebugs (previous failure)
2024/07/20 14:32:42 KRAKEND DEBUG: [SERVICE: Plugin Loader] Loading process completed
```

**Comment by fgil27** [comment]
Yes, this is a major issue, as I can’t upgrade to version 2.7.0 of Krankend because the plugins generated with the 2.7.0 version of the builder won’t load.

**Comment by taik0** [comment]
We are aware of the issue. We are rebuilding the 2.7.0 binaries to use the latest builder.

**Comment by taik0** [comment]
Docker containers and packages are already updated to use the latest Golang version (1.22.5) and now matches the version used by the krakend-builder.
