### ISSUE TITLE
devopsfaith/krakend runs krakend as root

### ISSUE THREAD

**Issue by stevenh** [krakend/krakend-ce#919]
**Environment info:**

* KrakenD version: v2.7.0
* System info: docker version 27.1.1

**Describe the bug**
The official official docker image [devopsfaith/krakend](https://hub.docker.com/layers/devopsfaith/krakend/2.7.0/images/sha256-b7c7045e940932053ca3380067afba2fb46fe0a6db42f834ca9b3a35c5bc342e?context=explore) as listed in [repo readme](https://github.com/krakend/krakend-ce?tab=readme-ov-file#run) is actually not built using [make docker](https://github.com/krakend/krakend-ce/blob/master/Makefile#L74) target from this repo. 

The impact of this is the krakend process being run as root not the krakend user as expected from the [Dockerfile](https://github.com/krakend/krakend-ce/blob/master/Dockerfile#L24).

**Comment by stevenh** [comment]
It also exposes a different port 8080 instead of 8000.

**Comment by kpacha** [comment]
I'm no sure about that dockerfile listed at the docker hub, but you can check that in fact the binary in the docker image is running using the `krakend` user by following these steps:

1. start a krakend container
2. in another console, just execute `docker exec -it <name_of_the_container> ps`

You'll get something like this:
```
PID   USER     TIME  COMMAND
    1 krakend   0:01 krakend run -dc krakend.json
   36 root      0:00 ps
```

**Comment by stevenh** [comment]
Sorry, when I said "runs krakend" I actually meant runs commands, so if you use it as a base RUN lines run as root and not krakend e.g.
Example Dockerfile:
```
ARG KRAKEND_IMAGE=devopsfaith/krakend:2.7.0
FROM ${KRAKEND_IMAGE}

RUN id
```

Docker build:
```
BUILDKIT_PROGRESS=plain docker build --no-cache -f ../../Dockerfile.krakend .
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile.krakend
#1 transferring dockerfile: 84B done
#1 DONE 0.0s

#2 [internal] load metadata for docker.io/devopsfaith/krakend:2.7.0
#2 DONE 0.0s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [1/2] FROM docker.io/devopsfaith/krakend:2.7.0
#4 CACHED

#5 [2/2] RUN id
#5 0.186 uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video)
#5 DONE 0.2s

#6 exporting to image
#6 exporting layers 0.0s done
#6 writing image sha256:e231f5918af4b87fb4d3a8fecfdd0934f5f02e409cd8c290ea0b6b3b9aadfe30 done
#6 DONE 0.0s
```

If I do the same with an image built from `make krakend` I get:
```
BUILDKIT_PROGRESS=plain docker build --no-cache --build-arg KRAKEND_IMAGE=krakend:local -f ../../Dockerfile.krakend .
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile.krakend
#1 transferring dockerfile: 119B done
#1 DONE 0.0s

#2 [internal] load metadata for docker.io/stevenhartland/krakend:2.7.0
#2 ...

#3 [auth] stevenhartland/krakend:pull token for registry-1.docker.io
#3 DONE 0.0s

#2 [internal] load metadata for docker.io/stevenhartland/krakend:2.7.0
#2 DONE 1.3s

#4 [internal] load .dockerignore
#4 transferring context: 2B done
#4 DONE 0.0s

#5 [1/2] FROM docker.io/stevenhartland/krakend:2.7.0@sha256:275e7480ad2f0faf2674983a5a1f69118c499220cc2dd4eede97cc7578482f98
#5 resolve docker.io/stevenhartland/krakend:2.7.0@sha256:275e7480ad2f0faf2674983a5a1f69118c499220cc2dd4eede97cc7578482f98 done
#5 DONE 0.0s

#6 [2/2] RUN id
#6 0.275 uid=1000(krakend) gid=65533(nogroup) groups=65533(nogroup)
#6 DONE 0.3s

#7 exporting to image
#7 exporting layers done
#7 writing image sha256:60ac4c22ac548309f825aa56fe7b27e75e4b92e31e42166f31e2898148070c59 done
#7 DONE 0.0s
```

As you can see the former reports `uid=0(root) gid=0(root)` where as the latter reports `uid=1000(krakend) gid=65533(nogroup) groups=65533(nogroup)`

**Comment by stevenh** [comment]
Overall consumers of krakend-ce don't seem to be able replicate the build as published to `devopsfaith/krakend` using the Makefile commands as they would expect.

**Comment by taik0** [comment]
Hi, this Dockerfile is old and still in the repo for people who just want to build the code and not to download a precompiled binary from the github releases page.
This Dockerfile is provided as simple as possible and everything runs as the krakend user.

The official docker image uses [this repo](https://github.com/krakend/docker-library/blob/master/2.7.0/Dockerfile) to build reproducible containers following the official Docker guidelines, using an entrypoint script that runs all the krakend commands as `krakend` and all the others as root.

**Comment by stevenh** [comment]
Thanks for reply @taik0 that clarifies what I'm seeing, appreciated!

Would you accept a PR to document that to avoid confusion for others?

**Comment by taik0** [comment]
Of course! That would be perfect.
