### ISSUE TITLE
Pass Traceparent Header in custom http requests in lua scripts

### ISSUE THREAD

**Issue by crazy-stardusts** [krakend/krakend-ce#921]
I have opentelemetry configured in all my services.

Before every request goes to backend in krakend, I need to call an api `A`. Currently I am using lua script to call `A`, but traceid for that call `A` is different from rest of that flow. Upon banging my head for hours, I am unable to pass traceparent header to the request. I can pass traceparent header, if it is in the original request, though it is not my use case.

I want to access trace-id in lua scipt.

**Comment by crazy-stardusts** [comment]
I have experience in c++, java, python, js, though little experience in go. But I need this urgently, please guide me, how to contribute and setup and find the relevant files to make this change.

**Comment by alombarte** [comment]
Plugins have access to traceIds. E.g.:
```go
ctx := req.Context()
spanCtx := trace.SpanContextFromContext(ctx)
logger.Debug("trace_id:", spanCtx.TraceID())
```
