### ISSUE TITLE
How to add custom fields to the log

### ISSUE THREAD

**Issue by Xuqy3** [krakend/krakend-ce#933]
I would like to be able to output some other information on the log, such as some traceId, clientId, etc. headers on the request. does kraken D support this?

**Comment by alombarte** [comment]
Hello @Xuqy3 , KrakenD does not support this because the access log is not configurable. The next version of KrakenD Enterprise will let you define and customize everything that shows up in the log.

**Comment by Xuqy3** [comment]
@alombarte Sorry to bother you again, can I report custom metrics in a custom plugin via the /metrics api interface to prometheus? Looking forward to your answer.

**Comment by alombarte** [comment]
Yes, you could report some metrics in a custom plugin
