### ISSUE TITLE
Error 500 "connection refused" with docker compose

### ISSUE THREAD

**Issue by Skawx** [krakend/krakend-ce#935]
**Environment info:**

* KrakenD version: Version 2.7.2 from devopsfaith/krakend:watch
* System info: docker compose
* Hardware specs: MacOs

**Describe the bug**
I use a docker-compose file with two services, keycloak and krakend : 
```dockerfile
version: '3.9'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-api-gateway
    ports:
      - "7080:8080"
      - "9001:9000"
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: "start-dev --features=admin-fine-grained-authz --import-realm --verbose --health-enabled=true"

  krakend:
    image: devopsfaith/krakend:watch
    container_name: krakend-gateway
    ports:
      - "11080:8080"
    volumes:
      - .:/etc/krakend/
    command: "run --config /etc/krakend/krakend.json"

networks:
  default:
    name: krakend-keycloak-ntw
``` 

My Keycloak container exposes a health/ready endpoint on port 9001 which returns a simple json message : 
![Capture d’écran 2024-10-16 à 18 29 39](https://github.com/user-attachments/assets/516a3833-7a3f-432b-ab6a-d0adf7b98785)

The two services are on the same network and as you can see in the krakend config file below I use the name of the keycloak service to define the host of the endpoint which is a problem for me.
When I call it (http://localhost:11080/ready) krakend returns me always an error 500 "connection refused".

![Capture d’écran 2024-10-16 à 18 26 30](https://github.com/user-attachments/assets/0951a899-e7b1-4af4-82c6-ce6d94c5dd67)

As you can see, the call is made on the container ip address of the keycloak service, so the replacement of the service name in the host declaration is well done. But it does not work.

**Your configuration file**:
```json
{
	"$schema": "https://www.krakend.io/schema/krakend.json",
	"version": 3,
	"name": "KrakenD - API Gateway",
	"timeout": "3000ms",
	"cache_ttl": "300s",
	"output_encoding": "json",
	"endpoints": [
		{
			"endpoint": "/ready",
			"method": "GET",
			"output_encoding": "no-op",
			"backend": [
				{
					"url_pattern": "/health/ready",
					"encoding": "json",
					"sd": "static",
					"method": "GET",
					"host": ["http://keycloak:9001"]
				}
			]
		}
	],
	"debug_endpoint": true,
	"echo_endpoint": true
}
```

If I replace the host name "keycloak" by the IP of my machine, all is ok, krakend returns the good result. 
I found the solution after long research on google (https://www.youtube.com/watch?v=ZGp-rM666KQ). 
It seems I'm not the only one facing this problem, I've never encountered it with any other docker-compose project.

Do I miss something or it is really a bug which needs to be fixed ?

Thx for having read.

**Comment by alombarte** [comment]
Hello @Skawx , your host is not pointing to the right port: `"host": ["http://keycloak:9001"]`. It should be `"host": ["http://keycloak:9000"]` because the containers communicate in the internal network, not in the port exposed in the host.

**Comment by Skawx** [comment]
Hello @alombarte, thank you so much. It works. My bad...
