### ISSUE TITLE
Adding Elestio as deployment option

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [krakend/krakend-ce#936]
Hey team,
I am Kaiwalya, Developer Advocate at Elestio. Elestio has been providing options of fully deploying and managing KrakenD application as shown [here](https://elest.io/open-source/krakend). I think it would be a great idea if we can add it to official readme/documentation here.
🔔 In addition to this, if you are interested we provide partnership opportunities with tools we support by **revenue share** upon addition of this method in docs. If you would like to collaborate, just shoot me an email at [kaiwalya@elest.io](mailto:kaiwalya@elest.io) :)

Example Button:

[![Deploy on Elestio](https://elest.io/images/logos/deploy-to-elestio-btn.png)](https://elest.io/open-source/krakend)

**Comment by alombarte** [comment]
Thank you for interest @kaiwalyakoparkar.

The repository is not currently open to sponsorship/endorsement from or to any third-party products or services in its README or the documentation. We don't even announce our own [Azure images](https://azuremarketplace.microsoft.com/ca/marketplace/apps/brutale.krakend-vm?tab=Overview) or [AWS image](https://aws.amazon.com/marketplace/pp/prodview-dgb4jeh3s62oy?sr=0-1&ref_=beagle&applicationId=AWSMPContessa).

For business opportunities please get in touch with sales@krakend.io

Thanks!
