### ISSUE TITLE
Add a new header to the requests of all endpoints

### ISSUE THREAD

**Issue by Skawx** [krakend/krakend-ce#939]
**Environment info:**

* KrakenD version: Version: 2.7.2
* System info: docker
* Backend technology: Node

**Describe what are you trying to do**:

i would like to add a new header to the requests of all endpoints.
In my example I named it "x-from-lua" like in the documentation example (https://www.krakend.io/docs/endpoints/lua) : 

```json
  {
    "version": 3,
    "extra_config": {
        "modifier/lua-endpoint": {
          "pre": "print('Lua service!'); local c = ctx.load(); c:headers('X-from-lua', '1234');"
        }
    }
  }
```

**Your configuration file**:

```json
{
	"version": 3,
	"name": "KrakenD - API Gateway",
	"timeout": "60000ms",
  "output_encoding": "json",
	"extra_config": {
    "modifier/lua-endpoint": {
			"pre": "local c = ctx.load(); c:headers('x-from-lua', '1234');"
    }
  },
  "endpoints": [
		{
			"endpoint": "/test",
			"method": "GET",
			"backend": [
				{
					"url_pattern": "/",
					"host": ["http://10.0.0.44:4005"],
					"encoding": "string"
				}
			]
		}
	]
}
```

When I check the headers in the request received by my backend the header does not exists.

I have tried to use it at endpoint level : 

```json
{
	"version": 3,
	"name": "KrakenD - API Gateway",
	"timeout": "60000ms",
  "output_encoding": "json",
  "endpoints": [
		{
			"endpoint": "/test",
			"method": "GET",
			"backend": [
				{
					"url_pattern": "/",
					"host": ["http://10.0.0.44:4005"],
					"encoding": "string"
				}
			],
"extra_config": {
    "modifier/lua-endpoint": {
			"pre": "local c = ctx.load(); c:headers('x-from-lua', '1234');"
    }
  }
		}
	]
}
```

but same thing, no "x-from-lua" header in my request.

If I use "lua-proxy" as below, all is ok. I can find my new header. but I want to change all my endpoint at the same time and not add extra_config for each one.

```json
{
	"version": 3,
	"name": "KrakenD - API Gateway",
	"timeout": "60000ms",
  "output_encoding": "json",
  "endpoints": [
		{
			"endpoint": "/test",
			"method": "GET",
			"backend": [
				{
					"url_pattern": "/",
					"host": ["http://10.0.0.44:4005"],
					"encoding": "string"
				}
			],
			"extra_config": {
				"modifier/lua-proxy": {
					"pre": "local r = request.load(); r:headers('x-from-lua', '1234');"
				}
			}
		}
	]
}
```
lua-proxy is not available at service level and it seems lua-endpoint does not affect request sent to backend.
I miss something but I don't know what. Could you help me to understand and to find a solution please ? 

Thank you for reading.

**Comment by taik0** [comment]
Hi @Skawx 

If you set the header at the endpoint level, add it to the `input_headers` so it's passed to the backend.
To avoid code repetition, we recommend using [flexible config](https://www.krakend.io/docs/configuration/flexible-config/)

Also, if the value you want to add is static, it's easier (and more performant) to use a [martian modifer](https://www.krakend.io/docs/backends/martian/).

**Comment by Skawx** [comment]
Hello @taik0, thank you for your answer I will have a look to flexible config.
