### ISSUE TITLE
Krakend check with linting enabled fails due to missing schema

### ISSUE THREAD

**Issue by ibevilinc** [krakend/krakend-ce#944]
**Environment info:**

* KrakenD version: 2.8.0
* System info: docker
* Hardware specs: n/a
* Backend technology: n/a
* Additional environment information: n/a

**Describe the bug**
krankend check with linting enabled fails due to a 404 error since the v2.8 schema is not publicly available.
```
ERROR compiling the schema:	jsonschema https://www.krakend.io/schema/v2.8/krakend.json compilation failed: https://www.krakend.io/schema/v2.8/krakend.json returned status code 404
```

**Commands used**
How did you start the software?
```
krakend check -c /tmp/krakend.json --lint
Parsing configuration file: /tmp/krakend.json
ERROR compiling the schema:	jsonschema https://www.krakend.io/schema/v2.8/krakend.json compilation failed: https://www.krakend.io/schema/v2.8/krakend.json returned status code 404
```

**Expected behavior**
Able to validate krakend configuration (ie run check with linting enabled) using latest 2.8.0 version

**Comment by alombarte** [comment]
Hi @ibevilinc , you upgraded to 2.8 before the pipeline pushed all the changes and it was even announced on the website, that was fast! :joy: 

The pipeline has now completed and should work OK
