### ISSUE TITLE
Gateway timeout return code 504

### ISSUE THREAD

**Issue by sylvainmouquet** [krakend/krakend-ce#949]
**Environment info:**

* KrakenD version: Run `krakend help | grep Version` and copy the output here
v2.8.0
* System info: Run `uname -srm` or write `docker` when using containers
docker
* Hardware specs: Number of CPUs, RAM, etc

* Backend technology: Node, PHP, Java, Go, etc.
external api
* Additional environment information:

**Describe the bug**

**Your configuration file**:

```json
{
  "$schema": "https://www.krakend.io/schema/v2.4/krakend.json",
  "version": 3,
  "name": "API Gateway - KrakenD",
  "port": 8080,
  "endpoints": [
    {
      "endpoint": "/time",
      "input_query_strings": [
        "timeZone"
      ],
      "backend": [
        {
          "host": ["https://timeapi.io"],
          "url_pattern": "/api/time/current/zone"
        }
      ]
    }
  ]
}

```

**Commands used**
How did you start the software?
```
#Example:
docker run --rm -it -v $PWD:/etc/krakend \
        -e FC_ENABLE=1 \
        -e FC_SETTINGS="/etc/krakend/config/settings" \
        -e FC_PARTIALS="/etc/krakend/config/partials" \
        -e FC_OUT=out.json \
        devopsfaith/krakend \
        run -c /etc/krakend/config/krakend.json -d
```
**Expected behavior**
The return status code is 500 but in case of gateway timeout, it should be 504 : https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/504
The error 'context deadline exceeded' is too generic, a more explicit error message could be displayed

**Logs**
If applicable, any logs you saw in the console and debugging information
[GIN] 2024/12/13 - 15:18:06 | 500 |  2.000455084s |     54.37.2.221 | GET      "/time?timeZone=Europe%2FAmsterdam"
Error #01: context deadline exceeded

**Comment by thedae** [comment]
Hi @sylvainmouquet 

KrakenD is not designed to function as a reverse proxy by default. To enhance security, it hides errors and status codes to prevent exposing backend details to end users. This behavior also applies to backend timeouts.

That said, you can override this default behavior by customizing backend errors and headers. Take a look at this:: https://www.krakend.io/docs/backends/detailed-errors/

**Comment by sylvainmouquet** [comment]
Hello @thedae 
Ok the api gateway has been designed for interaction with a frontend and security is set by default.
