### ISSUE TITLE
[Configuration]validator.chiper-suites enum  values may be more  frendly for humans

### ISSUE THREAD

**Issue by Hemiun** [krakend/krakend-ce#951]
**Version of KrakenD you are using**
2.8.0

**Is your feature request related to a problem? Please describe.**
Currently enum values for  validator.chiper-suites  array  (and also in other places of the configuration) looks like this
```
"enum": [
          5,
          10,
          47,
          53,
          60,
          156,
          157,
          49159,
          49161,
          49162,
          49169,
          49170,
          49171,
          49172,
          49187,
          49191,
          49199,
          49195,
          49200,
          49196,
          52392,
          52393
        ]
```
These values ​​are not very clear and require studying the source code to use.

**Describe the solution you'd like**
I think it is possible to replace this values ​​with more understandable string values.
For example,
```
TLS_AES_128_GCM_SHA256       uint16 = 0x1301
TLS_AES_256_GCM_SHA384       uint16 = 0x1302
TLS_CHACHA20_POLY1305_SHA256 uint16 = 0x1303
```
Also, a description of the values ​​can be added to the documentation.

**Comment by thedae** [comment]
Hi @Hemiun thanks for the feedback.

While the list of cipher suites might seem unclear at first, there’s no need to check the source code to find the ones you need. We’ve them already outlined in our documentation here: https://www.krakend.io/docs/authorization/jwt-validation/#cipher-suites.

If you're looking for more information about the ciphers themselves, there are some great tools available. For example https://ciphersuite.info/
